### ISSUE TITLE
In the cmakefile.txt, there is a library named SoWx, where can I find it?

### ISSUE THREAD

**Issue by asmwarrior** [famorcia/wxSceneViewer#2]
~~~~
find_package(Coin REQUIRED)
find_package(SoWx REQUIRED)
~~~~

For me, I'm mainly use msys2, and it has wx and coin library prebuilt(I can install them by pacman command). I'm not sure it is simple to build the SoWx library).

**Comment by asmwarrior** [comment]
[sowx](https://github.com/famorcia/sowx) this one?

I see this project is achieved, so you just drop the sowx project?

**Comment by famorcia** [comment]
Hello,
sorry for the late answer, I was not able to check before.
The proper project has been moved on [sowx](https://github.com/coin3d/sowx), so please for referring to it.

wxSceneViewer is in progress, I will put some screenshot as you suggestedx in next days.

Cheers

   Fab

**Comment by famorcia** [comment]
Hello, 
some feedback after testing on msys2.
First of all, prefer msw instead of gtk3.
Gtk3 does not provide gl module.
Remember --recurse-submodules when you will clone sowx.

I will continue testing on next days.

Cheers

   Fab

**Comment by asmwarrior** [comment]
Thanks for your response, especially I'd prefer msw under msys2. I'm hoping see your screen shot first.

**Comment by famorcia** [comment]
Hello, 
a screenshot coming from msys2 env has been provided on [wxSceneViewer](https://github.com/famorcia/wxSceneViewer)
For compiling I used the following options:

- sowx (this will install library on /opt)
cmake -DCMAKE_INSTALL_PREFIX=/opt <path of sowx sources>

- wxSceneViewer
cmake -DCMAKE_PREFIX_PATH=/opt/ <path of wxSceneViewer sources>

For running add  "/opt/bin/" to path:

PATH=$PATH:/opt/bin/

**Comment by asmwarrior** [comment]
> Hello, a screenshot coming from msys2 env has been provided on [wxSceneViewer](https://github.com/famorcia/wxSceneViewer) For compiling I used the following options:
> 
>     * sowx (this will install library on /opt)
>       cmake -DCMAKE_INSTALL_PREFIX=/opt
> 
>     * wxSceneViewer
>       cmake -DCMAKE_PREFIX_PATH=/opt/
> 
> 
> For running add "/opt/bin/" to path:
> 
> PATH=$PATH:/opt/bin/

Hi, thanks for the build instruction. I will try to those steps as soon as possible under my msys2.

BTW: I think the build instruction should be in the home page, what do you think? Thanks.

**Comment by asmwarrior** [comment]
I can now build the application under msys2.

Here are my steps:
First, I need to install the coin library by the command:

`pacman -S mingw-w64-x86_64-coin`

Note that I have already boost and wxWidgets library install in msys2.

Now, I switch to the cloned sowx library, and I have 
~~~~
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt -G "MinGW Makefiles"
mingw32-make.exe
mingw32-make.exe install
~~~~

Note that I I used the mingw32-make, which comes from this package([Package: mingw-w64-x86_64-make - MSYS2 Packages](https://packages.msys2.org/package/mingw-w64-x86_64-make)), 

Now, the sowx is installed to the msys2's /opt/ folder.

Now, I switch to the cloned wxSceneViewer repo, and

~~~~
  mkdir build
  cd build
  cmake ../ -DCMAKE_PREFIX_PATH=/opt/ -G "MinGW Makefiles"
  mingw32-make.exe
~~~~

With the above command, the final executable file is generated.

Now, I have to add the `PATH=$PATH:/opt/bin/`, so that the dlls from the sowx can be found.

Now, run the exe file in the `src/ ./wxSceneViewer.exe`, and load a file named `sox\models\coin_sowx.iv`

And the final result is shown below:

![image](https://github.com/famorcia/wxSceneViewer/assets/561818/ace106b9-4cc1-4827-826a-bd37acec15b2)

**Comment by asmwarrior** [comment]
Another question is:

What is the plan of this project, I see in the GUI, there are a lot of menus, but it looks like most of the menu items are not implemented yet.
